# playground.testinggggg.cricbid.online → /var/www/apps/testinggggg/frontend

server {
    listen 80;
    server_name playground.testinggggg.cricbid.online;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name playground.testinggggg.cricbid.online;

    ssl_certificate     /etc/letsencrypt/live/cricbid.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cricbid.online/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    root  /var/www/apps/testinggggg/frontend;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;
}
